name: Test Pipeline
on: [push, pull_request]

jobs:

  win_10:
    name: Test against Windows Server 2019
    runs-on: windows-2019
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 5


    steps:
      - uses: actions/checkout@v2
      - name: Install the Package
        run: |
          python3 -m pip install --upgrade pip
          pip3 install wheel
          pip3 install .[dev]
      - name: Run the example script x64
        run: python3 utils\example.py C:\hostedtoolcache\windows\Python\2.7.18\x64
      - name: Run the unit tests
        run: |
          python3 -m pytest -v test
        env:
          PY2_HOME: C:\hostedtoolcache\windows\Python\2.7.18\x64
