name: Test Pipeline
on: [push, pull_request]

jobs:

  ubuntu_2004:
    name: Test against Ubuntu 2004
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install git python2.7 libpython2.7-dev python3-pip
      - name: Install the Package
        run: pip3 install .[dev]
      - name: Run the unit tests
        run: pytest tests/
      - name: Run the example script
        run: python3 utils/example.py
